### ISSUE TITLE
Security Tracker for phase 1

### ISSUE THREAD

**Issue by psiinon** [mozilla/blurts-server#155]
Security recommendations from the RRA:

- [x] #133 Use DomPurify for unescaped data in the templates as well as when the data is added to the db
- [x] #156 Review 3rd party libs and remove any that aren’t needed (eg jquery)
- [x] #143 Hash emails on the client side and only send that to the service
- [x] #157 Plan load testing
- [x] #158 Consider connection pooling

**Comment by groovecoder** [comment]
Closing as the sub-tasks are closed.
