### ISSUE TITLE
Firefox Monitor: Dashboard > Add a new email

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#1931]
### Proposal

**Goal**
- Propose usability improvements to the add a new email flow for Firefox Monitor

**Subtasks**
- [x] Document existing add new email flow
- [x] Gather any relevant data and UER
- [x] Identify gaps in user flow based on user needs
- [x]  Propose improvements 

**Timeline**
Due Friday, September 25

**Comment by jwibowo** [comment]
@tcinotto - hiya! im jen from the dpx xd team and i will be picking up your ticket for FFX Monitor. 

**A few questions:**
1. Is there a folder with past research specific to FFX Monitor that you'd be able to share?
2. Is there an existing past PRD or vision doc/deck about Monitor that you'd be able to share? Would love to deepen my understanding of the product, how it came to be, target problems, target users, etc :) 
3. Any existing metrics?

Thanks in advance, excited to work with you!

**Comment by tcinotto** [comment]
Hi @jwibowo thank you for taking a look at this! 

1. Existing research can be found here by searching monitor: https://firefoxur.github.io/. I dont think I've seen a specific folder. 
2. I just took over as PM for monitor 2 weeks ago so much of the vision/prd might be out of date that we have. I am looking to build out a prd and vision doc/deck but I would like us first to define the prospector vision/mission then Firefox Monitor's. I want to ensure we're not cannibalizing or taking away from our upcoming services. Then once that prospector's vision/mission is determined I will be building out the vision for monitor. Right now I'm just looking at small modifications and low hanging fruit. This is the previous strategy though: https://docs.google.com/presentation/d/1So57WQRIMZAs8wsD1Lhapp6vqS8V4wr75ULwINygBMU/edit?usp=sharing 
3. https://earthangel-b40313e5.influxcloud.net/d/dEpkGp4Wz/fx-monitor?from=now-30d&orgId=1&refresh=1m&to=now I can also add you to GA if needed.

**Comment by jwibowo** [comment]
Awesomeee, thanks @tcinotto! One clarifying question– might be my newness so apologies. What is the prospector vision/mission?

**Comment by jwibowo** [comment]
Figma File: https://www.figma.com/file/Dxj3PfP5okxHUMssnxOz5X/Firefox-Monitor?node-id=0%3A1

**Comment by jwibowo** [comment]
Data on user email count: 

1.4M of our 8.1M  (17%) of Monitor subscribers have added an additional address. 
1.48M of those 1.49M (99%) have added 1-8 addresses, 
5.9K (0.3%) have added 9-15 addresses. 1.4M of our 8.1M  (17%) of Monitor subscribers have added an additional address. 
1.48M of those 1.49M (99%) have added 1-8 addresses, 
5.9K (0.3%) have added 9-15 addresses.

**Comment by jwibowo** [comment]
Data on when a user adds a new email (D1, D2, etc) and whether that influences retention (;tldr n/a):

![Screen Shot 2020-09-24 at 4.23.59 PM.png](https://images.zenhubusercontent.com/5f5924ee55cf57088e41149b/f32cb9a3-760e-4118-9621-14f6918017aa)

**Comment by jwibowo** [comment]
UR relevant to add a new email (slides 46-50)
https://docs.google.com/presentation/d/1s_6oUYs_F4IWblU9bAJTp6A6mzGXNPQ2SaJsPtwdFH4/edit#slide=id.g899f05de7c_0_42

**Comment by jwibowo** [comment]
@tcinotto @malqinneh @lesleyjanenorton 

Hi, I've started working on a few quick ideas around how we might improve our add a new email flow in FFX Monitor. These are v1 ideas and open to any and all feedback. Please add your feedback and/or any questions directly to the Figma file using the commenting tool. This will require a Figma guest account if you do not already have one. Feel free to ping me for help setting it up if needed. 

Will add context that this is a lower priority ticket amongst other S&P efforts. TBD on next steps (i.e user testing, strategic planning, etc.)

Figma file: https://www.figma.com/file/cAiqz4mVy28DjSC23nncJI/Monitor-Add-new-email?node-id=0%3A1

**Comment by tcinotto** [comment]
Thank you! Just reviewed and provided comments on the opportunities.

**Comment by jwibowo** [comment]
Feedback is in :-). Big thanks to all who provided. 

Typically, the next steps would be to move the proposals that we are all collectively interested in into user testing (usertesting.com). I could take the lead on this and loop in research. 

However, with Monitor being de-prioritized in light of VPN/Prospector work, my recommendation would be to hold on any updates until the future and strategy of Monitor is finalized.

**Comment by tcinotto** [comment]
@jwibowo Thank you! I think I would like to move ahead with moving the add another email address higher up and making it not look like a newsletter sign up. I think we could make some assumptions and monitor in analytics pre/post additional email sign ups (without doing UT). Out of the mocks that you provided is there one that you prefer based off of your UX experience? (@lesleyjanenorton do you want to review the proposed mock ups in https://www.figma.com/file/cAiqz4mVy28DjSC23nncJI/Monitor-Add-new-email?node-id=0%3A1 to provide technical feasibility input?)

**Comment by OddHouseGames** [comment]
Hi All, been seeing a lot of community feedback about the removal of the 'add email' button once a user hits their limit.

UX-wise, it would be best if removing the text referencing adding more emails, to have text '5/5 limit reached' to avoid this user confusion/frustration.

Also, seeing lots of situations where the limit is not enough, has Mozilla/FF considered offering a paid version to allow for adding more?

Either way, improving the feedback to the user when hitting the limit will help solve a lot of these community confusion/frustration issues, as they are just hitting a wall and not knowing why.

**Comment by EMMLynch** [comment]
Closing since we've redesigned the site and functionality since this was created. If you feel that this is still needed, please let me know.
