### ISSUE TITLE
Firefox Monitor: As a stakeholder, I'd like to know what users do or would want to do when they receive a breach email notification from Firefox Monitor

### ISSUE THREAD

**Issue by tcinotto** [mozilla/blurts-server#1933]
### Proposed project plan

**Goal**

- Identify action(s) users make when they receive an email from Firefox Monitor notifying them that their email address was implicated in a known security breach
- Identify user needs when they receive an email from Firefox Monitor notifying them that their email address was implicated in a known security breach

**Subtasks**

- [x] Sync with research to identify possible ways to surface user needs/expectations
- [x] Ask Michael from legal about following up with Monitor users
- [x] Complete research [outline](https://docs.google.com/document/d/1erHF3TJwXoftLlexiXP2O2zwtno0s1OADJSV04o9WoA/edit?usp=sharing) for research team
- [x] Sync back with Tony to share plan for conducting research
- [ ] Update issue with next steps (based on Research timeline)

**Timeline**

- Next steps due Friday, September 18

**Related issues**

- [Firefox Monitor: Resolve known security breaches #1932](https://app.zenhub.com/workspaces/experience-design-5f58057dfb3d02001259cefb/issues/mozilla/blurts-server/1932)

**Additional context**

Many users from qualitative research see Firefox Monitor as a set it and forget it service, but then find value when they are alerted about breaches. These alerts come in the form of an email. Can we do explorations or even research what a user does or would want to do when they receive these emails? I might make the assumption that users could feel some fear, annoyance, frustration, and confusion when receiving a breach alert notification what can we do to help them and make it easy for them in this potentially vulnerable state?

**Comment by malqinneh** [comment]
@tcinotto @groovecoder @lesleyjanenorton 

After speaking with Gloria about how might we capture qualitative user research re: Firefox Monitor emails, we have some questions:

1. Would it be possible to reach out to users that have *recently* been notified of a breach and ask them to schedule a time (with us via Validately) to talk about their experience?
2. Would it be possible (or better) to send an optional survey to those users to capture their feedback?
3. Do we use Bugzilla or anything similar to track user feedback/issues that we might look at for this ask?
4. Is there a way to avoid reaching out to users that have *recently* been notified of a breach for something that is highly sensitive and so it might be awkward talking about (ie. personal or financially related services)?

**Comment by lesleyjanenorton** [comment]
1.) From an engineering standpoint, it's feasible. We'd probably need to square it with legal though because I think there are pretty significant limitations to what we can and cannot send.
2.) Same as above.
3.) We use GitHub to track issues but users rarely provide feedback there. When users reply to Firefox Monitor emails, those replies are forwarded to and triaged by Zendesk.
4.) Yes, we can detect if their most recent breach was marked "Sensitive" and/or if it exposed x, y, z data classes.

**Comment by malqinneh** [comment]
Below is from Michael Feldman (legal):

> If we want to post a link on Discourse or put a link on the monitor webpage to ask for users to contact us, we can definitely do that. 
> 
> If we want to email out a survey, we have to have the user's consent to send that email. So they'd have to be a part of one of our email lists that allows marketing emails like surveys. That would probably be the Mozilla Labs list or the New Product Testing list.

**Comment by tcinotto** [comment]
Thank you @malqinneh for all the great progress! I'm going to ask marketing about their email channels and see if there is maybe a creative solution we can leverage. I'll respond here with updates.

**Comment by malqinneh** [comment]
Np! We can definitely help with this ask - it's just that we're
collaborating with research. I'll check in on their timeline on Monday.

**Comment by tcinotto** [comment]
@malqinneh Would we want this to be English only for research?

**Comment by malqinneh** [comment]
@tcinotto great question!

Checked in with Gloria on this; we'll need to find out if we need to localize the survey(s). If we can make it work with just English for now - that would be best for getting the survey launched sooner. Again, something Gloria will determine once we kick-off research (likely next week).

**Comment by malqinneh** [comment]
@isobelroe assigned this ticket to you - should we schedule a kickoff for the research in the [outline](https://docs.google.com/document/d/1erHF3TJwXoftLlexiXP2O2zwtno0s1OADJSV04o9WoA/edit?usp=sharing)?

**Comment by malqinneh** [comment]
@tcinotto closing this issue as there isn't anything specific that has been started yet and Research won't be able to support due to resourcing.
