### ISSUE TITLE
Launch day checklist

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-server#416]
We would like to deploy with on-the-sly DNS record first and then switch it over, if possible. (May be tricky with the SES and HIBP callback setups)

### Before DNS switch
* [x] Ensure all [environment variables are set for prod](https://gist.github.com/groovecoder/0ce143af8b50514f4dcf904a4a931811)
   * Also these:
      *  `MOZLOG_FMT="heka"`
      * `MOZLOG_LEVEL="info" `
* [x] Execute db migrations on production DB
   * `knex --knexfile db/knexfile.js migrate:latest`

### After DNS switch
3. SES Config
   * [x] Set `SES_NOTIFICATION_LOG_ONLY=1`
   * [x] Set up SES and verify the SES callback sent to production URL via server logs
   * [x] After verification, change `SES_NOTIFICATION_LOG_ONLY=`
4. HIBP Callback Config
   * [x] Set the HIBP callback URI to production
      * `curl --data '{callbackUri:"https://monitor.firefox.com/hibp/notify"}' https://api.haveibeenpwned.com/callback/seturi?code=[api key]`
